version: "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "8111:8081"
      # - "443:443"
    restart:
      always
    volumes:
      - wp:/var/www/html/wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart:
      always
    volumes:
      - wp:/var/www/html/wordpress

volumes:
    wp:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/karim/data
