version: "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
      # - "443:443"
    restart:
      always
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart:
      always
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - inception_network
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart:
      always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network

volumes:
    wp_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/karim/Desktop/data/wordpress
    db_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/karim/Desktop/data/database

networks:
  inception_network:
    name: inception_network
    driver: bridge
