version: "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "8111:8081"
      # - "443:443"
    restart:
      always
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart:
      always
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - network
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart:
      always
    volumes:
      - database:/var/lib/mysql
    networks:
      - network

volumes:
    wp:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/karim/data/wp
    database:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/karim/data/database

networks:
  network:
    name: network
    driver: bridge
