FROM alpine:latest

# COPY index.html /usr/share/nginx/html

WORKDIR /

RUN apk update && apk add nginx



# Make port 80 available to the world outside this container
# EXPOSE 80

# Define environment variable
# ENV NAME World

CMD [ "" ]